# Generated by Django 6.0.2 on 2026-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=False, help_text='Indica se o usuário precisa trocar a senha no próximo login', verbose_name='Precisa Trocar Senha'),
        ),
    ]
