# Generated by Django 6.0.2 on 2026-02-21 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação de Reserva'), ('cancelamento', 'Cancelamento de Reserva'), ('lembranca', 'Lembrança de Reserva'), ('atualizacao', 'Atualização de Reserva')], default='confirmacao', max_length=20, verbose_name='Tipo de Notificação')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='reservas.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['usuario', 'lido'], name='reservas_no_usuario_21d846_idx'), models.Index(fields=['usuario', '-data_criacao'], name='reservas_no_usuario_bd32fc_idx')],
            },
        ),
    ]
